---
- name: Install Java 17 (required for Jenkins 2.361+)
  dnf:
    name: java-17-amazon-corretto-headless
    state: present

- name: Set Java 17 as default
  alternatives:
    name: java
    path: /usr/lib/jvm/java-17-amazon-corretto/bin/java
