---
- name: Mount Jenkins home EBS volume
  import_tasks: mount-ebs.yml

- name: Install Java
  import_tasks: java.yml

- name: Install Jenkins
  import_tasks: install.yml

- name: Install Jenkins plugins
  import_tasks: plugins.yml

- name: Configure Jenkins via JCasC
  import_tasks: configure.yml

- name: Configure Kubernetes agent cloud
  import_tasks: k8s-agent.yml
