apiVersion: v2
name: microservice8
description: Helm chart for microservice8
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Jeevagan
keywords:
  - jeevagan
  - microservice
