apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.image.repository }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.image.repository }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.image.repository }}
