apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.image.repository }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 80
  type: {{ .Values.service.type }}
