replicaCount: 2

image:
  tag: staging-latest

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 384Mi

hpa:
  minReplicas: 2
  maxReplicas: 5

ingress:
  host: microservice1.staging.internal.telstra.com

env:
  APP_ENV: staging
