apiVersion: v1
kind: Service
metadata:
  name: microservice11
  namespace: microservice11
  labels:
    app: microservice11
    project: telstra
spec:
  selector:
    app: microservice11
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
