replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 384Mi

hpa:
  minReplicas: 2
  maxReplicas: 5

ingress:
  host: microservice3.staging.internal.jeevagan.com

env:
  APP_ENV: staging
