apiVersion: v1
kind: Service
metadata:
  name: microservice12
  namespace: microservice12
  labels:
    app: microservice12
    project: telstra
spec:
  selector:
    app: microservice12
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
