replicaCount: 1

image:
  tag: dev-latest

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  minReplicas: 1
  maxReplicas: 3

ingress:
  host: microservice2.dev.internal.telstra.com

env:
  APP_ENV: development
