# Alerting rules for CPU usage
groups:
- name: cpu_usage.rules
  rules:
  - alert: HighCpuUsage
    expr: avg(rate(container_cpu_usage_seconds_total[1m])) > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High CPU usage for container {{ $labels.container }}
