apiVersion: v1
kind: Service
metadata:
  name: microservice5
  namespace: microservice5
  labels:
    app: microservice5
    project: telstra
spec:
  selector:
    app: microservice5
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
