apiVersion: v1
kind: Service
metadata:
  name: microservice1
  namespace: microservice1
  labels:
    app: microservice1
    project: telstra
spec:
  selector:
    app: microservice1
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
