apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kibana-credentials
  namespace: elk-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: kibana-secret
    creationPolicy: Owner
  data:
    - secretKey: KIBANA_USER
      remoteRef:
        key: dev/kibana/credentials
        property: KIBANA_USER
    - secretKey: KIBANA_PASSWORD
      remoteRef:
        key: dev/kibana/credentials
        property: KIBANA_PASSWORD
    - secretKey: KIBANA_ENCRYPTION_KEY
      remoteRef:
        key: dev/kibana/credentials
        property: KIBANA_ENCRYPTION_KEY
    - secretKey: KIBANA_REPORTING_KEY
      remoteRef:
        key: dev/kibana/credentials
        property: KIBANA_REPORTING_KEY
