apiVersion: v1
kind: Service
metadata:
  name: microservice9
  namespace: microservice9
  labels:
    app: microservice9
    project: telstra
spec:
  selector:
    app: microservice9
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
