apiVersion: v2
name: microservice6
description: Helm chart for microservice6
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Jeevagan
keywords:
  - telstra
  - microservice
