apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: microservice13
  namespace: microservice13
  labels:
    app: microservice13
    project: telstra
spec:
  podSelector:
    matchLabels:
      app: microservice13
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector:
            matchLabels:
              app: microservice13
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app: microservice13
      ports:
        - protocol: TCP
          port: 8080
