# Logstash Configuration
input {
  beats {
    port: 5044
  }
}
filter {
  grok {
    match => { "message" => "%{HTTPDATE:timestamp} %{IPORHOST:client_ip} %{WORD:method} %{URIPATH:request_uri} %{NUMBER:status}"
    }
  }
output {
  elasticsearch {
    hosts => ["es:9200"]
    index => "applogs-%{+yyyy.MM.dd}"
  }
}