apiVersion: v1
kind: Service
metadata:
  name: microservice7
  namespace: microservice7
  labels:
    app: microservice7
    project: telstra
spec:
  selector:
    app: microservice7
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
